version: "3.8"

services:
  php:
    build: ./backend
    container_name: php
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: tracker_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  frontend:
    build: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - nginx
    command: ["npm", "run", "dev"]

volumes:
  mysql-data: